apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kolada-mcp-ingress
  labels:
    app: kolada-mcp
  annotations:
    spec.ingressClassName: "traefik"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    traefik.ingress.kubernetes.io/redirect-entry-point: "https"
    traefik.ingress.kubernetes.io/router.middlewares: mcp-strip-kolada-prefix@kubernetescrd
spec:
  tls:
    - hosts:
        - mcp-k8s.intric.ai
      secretName: kolada-mcp-tls
  rules:
    - host: mcp-k8s.intric.ai
      http:
        paths:
          - path: /kolada
            pathType: Prefix
            backend:
              service:
                name: kolada-mcp-service
                port:
                  number: 80
